name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login --username ryanb1303 --password ${{ secrets.GH_TOKEN }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/bappeda-dev-team/notulen-frontend:latest
        docker push ghcr.io/bappeda-dev-team/notulen-frontend:latest
